project:
  type: website
  output-dir: docs
  render:
    - src/index.qmd
    - src/chessrank.qmd
    - src/learning-by-gradient-descent.qmd
    - src/counting-is-hard.qmd
    - src/breaking-caesar-cipher.qmd
    - src/history-of-language-models.qmd
    - src/path-to-gpt.qmd

website:
  navbar:
    background: primary
    left:
      - text: "Home"
        href: src/index.qmd
      
format:
  html:
    theme: journal
    fontsize: 1.2em
    toc: true
    code-fold: false
    callout-appearance: minimal
    css: styles.css
