[tool.poetry]
name = "vikasgorur-github-io"
version = "0.1.0"
description = ""
authors = ["Vikas Gorur <vikas@airbase.io>"]
readme = "README.md"
packages = [{include = "vikasgorur"}]

[tool.poetry.dependencies]
python = "^3.11"
jupyterlab = "^4.2.0"
torch = "^2.3.0"
pandas = "^2.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
