[tool.poetry]
name = "vikasgorur-github-io"
version = "0.1.0"
description = ""
authors = ["Vikas Gorur <vikas@airbase.io>"]
readme = "README.md"
packages = [{include = "vikasgorur"}]

[tool.poetry.dependencies]
python = "^3.11"
jupyter = "^1.0.0"
webio-jupyter-extension = "^0.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
