# Stats 110: Practice 1

Exercises from Chapter 1 of @blitzsteinIntroductionProbability2019

::: {.callout-note}
6. There are 20 people at a chess club on a certain day. They each find opponents and start playing. How many possibilities are there for how they are matched up, assuming that in each game it _does_ matter who has the white pieces?
:::

Let the players be numbered $1..20$. Each permutation of the list can be considered a pairing, if you draw bars like so:

$$
1 \, 3 \, | \, 4 \, 6 \, | \, 2 \, 5  \,|\, ...
$$
The total number of permutations is $20!$

Each pair like $|1\,3|$ is two people sitting down at a table for a game, with white and black pieces respectively. The order within a pair matters. However, the order of tables themselves doesn't matter. There are $10!$ ways to permute the tables, and all those must be considered equivalent.

Thus the total number of ways to match 20 people up is: $\frac{20!}{10!}$.

::: {.callout-note}
8. You are ordering two pizzas. A pizza can be small, medium, large, or extra large, with any combination of 8 possible toppings (getting no toppings is allowed, as is getting all 8). How many possibilities are there for your two pizzas?
:::


