---
title: Mysore Food Guide
---

_Last updated_: Dec 22, 2024.

---
These are my opinions but they are also correct.

**Rating scale:**

This is loosely based on the Michelin system, in which three means "a destination", two means "worth a detour" and one means "very good".

| Rating | Interpretation                                                                                                                    |
|--------|-----------------------------------------------------------------------------------------------------------------------------------|
| ★★★    | A place with a distinct identity or uniquely Mysore flavor. These are the places you should prioritize if you're visiting Mysore. |
| ★★     | The best place in Mysore for a specific category. Consult this list if you're craving something specific (e.g., pizza).           |
| ★      | Acceptable. Use this list if you just need to grab something quick nearby.                                                        |

<!-- just for vspace -->
<div />

## Three star

★★★ **Cafe CCBC** \
_The most authentic Mysore breakfast_ ([map](https://maps.app.goo.gl/oheiMASuWMHZne3t9))

<div class="indent">
CCBC serves the kind of breakfast you'd get in a Mysore household. Try the flagship chow chow baath, a classic combo of a sweet (kesari baath) and a savoury (khaara baath) rava pudding. You might think that you don't like kesari baath, but you might have never eaten the real thing. Most darshinis don't use real saffron in their kesari baath, but CCBC does.

Also try their dosa. It's smaller and softer, the way it's made in homes. Quite different from the masala dosa you find in restaurants.
</div>

★★★ **Gayatri Tiffin Room (GTR)** \
_Dosa with a long-standing reputation_ ([map](https://maps.app.goo.gl/rLYqUp4jJmJd5gPW9))

<div class="indent">
Beloved by generations of Mysoreans for their morning dosa. Best paired with a robust hike up the steps of Chamundi hill ([start here](https://maps.app.goo.gl/Mse6Vm3zfQPxwPkKA)). Pro-tip: skip the crowds at the much-hyped Mylari dosa and go to GTR instead. Mylari is a worthwhile experience on its own but its hype has far overtaken its quality.
</div>

★★★ **SAPA** \
_Bakery, lunch & dinner, desserts_ ([map](https://maps.app.goo.gl/BbfK8VUvm225Bp2j6))

<div class="indent">
A Mysore institution. Set in a converted old bungalow with outdoor and indoor seating. The only place to get good European style breads (sourdough is the house specialty). Excellent savoury dishes and fantastic desserts.
</div>

★★★ **Little Alwar's Bakehouse** \
_Desserts and savoury_ ([map](https://maps.app.goo.gl/atRmDXeZ2TuXsxsE7) • [Instagram](https://www.instagram.com/littlealwars_bakehouse/))

<div class="indent">
A take-away bakery run by a woman with true passion for her craft. Check Instagram for opening hours and weekly menus. Everything is guaranteed to be good.
</div>

★★★ **burgerie** \
_Comforting vegan burgers and lunch_ ([map](https://maps.app.goo.gl/ZJuqMNStQXGNt8Mm6))

<div class="indent">
A passionate chef cooks a limited menu of burgers and lunch bowls. The rice & dal lunch bowls are the embodiment of the flavors of south Karnataka cuisine. 
</div>

★★★ **Upahara Darshini** \
_Evening snacks_ ([map](https://maps.app.goo.gl/q99qpT1L4rsscorj8))

<div class="indent">
Despite the name, this is not a darshini. They only serve a small menu of deep-fried snacks and are only open 5pm - 9pm. Best to get there between 5-7pm before they start running out of stuff. Try the masala vada, deep fried chickpea snack, kind of like a falafel.
</div>

## Two star
★★ **The Old House** \
_Pizza, salads, gelato_ ([map](https://maps.app.goo.gl/dvGqw2GBHnp4vgKU8))

<div class="indent">
Decent vegetarian pizza and salads. Good coffee and omelettes. They also have a lovely gelato parlor that makes you feel like you're on a Wes Anderson movie set.
</div>

★★ **Poojari Fish Land** \
_Kerala and Mangalore-style seafood_ ([map](https://maps.app.goo.gl/ttYdG8M1VW1rNpaA6))

<div class="indent">
A huge place on the Bangalore highway, just outside of Mysore. Good fish curry, grilled and fried fish, ghee roast.
</div>

★★ **Basaveshwar Khanavali** \
_North Karnataka style jowar roti meals_ ([map](https://maps.app.goo.gl/5xRD9mDPXUhDACMo7))

<div class="indent">
Best place in Mysore for North Karnataka-style jowar roti meals, part of the same chain that exists in Bangalore and other places.
</div>

★★ **Depth N Green**  \
_Smoothies, sandwiches_ ([map](https://maps.app.goo.gl/Y64FNE4Km69ntQi36))

<div class="indent">
A vegan-ish cafe catering to the yoga crowd, in the hip part of town. Their smoothies and juices are fantastic.
</div>


★★ **Minimal Coffee Roasters** \
_Coffee_ ([map](https://maps.app.goo.gl/AtZg9PQz6JwmcPnVA))

<div class="indent">
The best coffee in Mysore and baristas who know what they're doing. Not much seating and no food. They also sell their own beans and brewing equipment.
</div>

★★ **Metropole Hotel** \
_Lunch and dinner_ ([map](https://maps.app.goo.gl/okgKot3izadYVaGY9))

<div class="indent">
Metropole is on this list more for its ambience than the food. It is by far the best place in Mysore
to have a _quiet_, relaxed conversation. The food is typical North Indian fare and is decent. Anything
made in the tandoor is especially good. My favorites are the kalmi kabab and the fish tikka.
</div>


## One star

★ **Green Leaf** \
_South Indian_ ([map](https://maps.app.goo.gl/JDun1Z9Pb4tqQnii6))

<div class="indent">
Casual sit-down South Indian place that's been there for 20+ years. I like their poori for breakfast.
</div>

★ **TKS Iyengar** \
_South Indian_ ([map](https://maps.app.goo.gl/VSSuRGJKz9hdEgLd8))

<div class="indent">
As the name implies, this is authentic Brahmin cuisine. In the popular culture this cuisine is often thought of as being representative of all of Karnataka, but our country is more diverse than that. Good bisi bele baath.
</div>

★ **Kapoor's Cafe** \
_Punjabi_ (multiple locations)

<div class="indent">
The same chain that exists in Bangalore. Good Punjabi food. I've never eaten in Punjab so I'm no expert on this.
</div>

★**Rongkup's Lee Restaurant** \
_Indo-Chinese_ ([map](https://maps.app.goo.gl/mhwgSpSdhb8UJTgDA))

<div class="indent">
Decent Indo-Chinese food.
</div>
