project:
  type: website
  output-dir: ../docs
  execute-dir: project
  preview:
    port: 14000
  render:
    - index.qmd
    - posts/for-a-kannada-movie.qmd
    - posts/simplest-autoencoder.qmd
    - posts/learning-by-gradient-descent.qmd
    - posts/counting-is-hard.qmd
    - posts/breaking-caesar-cipher.qmd
    - posts/path-to-llms.qmd
    - posts/feature-flags.qmd
    - posts/chessrank.qmd
    - posts/mysore-food-guide.qmd
    - annotations/history-of-language-models.qmd
    - annotations/programming-as-theory-building.qmd
    - annotations/why-machines-learn.qmd
    - programs-for-humans/advent-of-code-2024.qmd
    - programs-for-humans/cryptopals-set1.qmd
    - exercises/stats110-practice1.qmd

bibliography: /Users/vikas/study/gorur.dev/src/zotero.bib
csl: chicago-with-urls.csl

website:
  navbar:
    background: primary
    left:
      - text: "Home"
        href: index.qmd
  reader-mode: true

format:
  html:
    theme: journal
    fontsize: 1.2em
    toc: false
    code-fold: false
    highlight-style: arrow
    callout-appearance: minimal
    css: styles.css
