project:
  type: website
  output-dir: docs
  execute-dir: project
  render:
    - index.qmd
    - posts/learning-by-gradient-descent.qmd
    - posts/counting-is-hard.qmd
    - posts/breaking-caesar-cipher.qmd
    - annotations/history-of-language-models.qmd
    - posts/path-to-gpt.qmd

website:
  navbar:
    background: primary
    left:
      - text: "Home"
        href: index.qmd
  reader-mode: true
      
format:
  html:
    theme: journal
    fontsize: 1.2em
    toc: true
    code-fold: false
    callout-appearance: minimal
    css: styles.css
