project:
  type: website
  output-dir: ../docs
  execute-dir: project
  preview:
    port: 14000
  render:
    - index.qmd
    - posts/makemore-1.qmd
    - posts/makemore-1a.qmd
    - posts/makemore-2.qmd
    - posts/for-a-kannada-movie.qmd
    - posts/simplest-autoencoder.qmd
    - posts/learning-by-gradient-descent.qmd
    - posts/counting-is-hard.qmd
    - posts/breaking-caesar-cipher.qmd
    - posts/path-to-llms.qmd
    - posts/feature-flags.qmd
    - posts/chessrank.qmd
    - posts/mysore-food-guide.qmd
    - posts/varieties-of-silence.qmd
    - posts/secret-sharing-in-apl.qmd
    - posts/blogs-by-humans.qmd
    - posts/worse-is-better.qmd
    - posts/static-ui-is-dead.qmd
    - annotations/biology-of-llm.qmd
    - annotations/deep-dive-into-llms.qmd
    - annotations/history-of-language-models.qmd
    - annotations/programming-as-theory-building.qmd
    - annotations/why-machines-learn.qmd
    - programs-for-humans/advent-of-code-2024.qmd
    - programs-for-humans/cryptopals-set1.qmd
    - programs-for-humans/project-euler.qmd
    - programs-for-humans/cryptopals-set1-rust.qmd
    - exercises/stats110-practice1.qmd

bibliography: /Users/vikas/study/gorur.dev/src/zotero.bib
csl: chicago-with-urls.csl

website:
  navbar:
      background: primary
      search: false
      left:
        - text: "Home"
          href: index.qmd

format:
  html:
    theme: journal
    fontsize: 1.1em
    code-fold: false
    highlight-style: haddock
    callout-appearance: minimal
    css: styles.css
