---
title: "Vikas Gorur"
format:
    html:
        code-fold: true
---

Engineering at [Airbase](https://www.airbase.com/), previously Twitter, Blurb, Gluster.

[@vikasgorur](https://x.com/vikasgorur)

## Machine Learning

This is my attempt to build the "tech tree" of ML, starting from the absolute basics and ending up somewhere around GPT-4.

<span class="pub-date">2024-10-18</span> [Path to LLMs](posts/path-to-llms.qmd)

<span class="pub-date">2024-09-01</span> [Breaking Caesar ciphers using relative entropy](posts/breaking-caesar-cipher.qmd) \
<span class="pub-date">2024-08-31</span> [Learning by gradient descent](posts/learning-by-gradient-descent.qmd)

## Applied Math

<span class="pub-date">2024-10-28</span> [chessrank: who should win a tournament?](posts/chessrank.qmd) \
<span class="pub-date">2024-07-24</span> [Counting is hard](posts/counting-is-hard.qmd)

## Annotations

My notes on papers and articles I've read.

<span class="pub-date">2024-10-07</span> [History of Language Modeling](annotations/history-of-language-models.qmd)

## Exercises
<span class="pub-date">2024-11-02</span> [Stats 110: Practice 1](exercises/stats110-practice1.qmd)

## Misc

<span class="pub-date">2020-04-30</span> [How to do Feature Flag-Driven Development](posts/feature-flags.qmd)

